Bugfix for "ns_http connect": Linux sometimes returned error (false positive)
Sometimes "ns_http run SOMEHOST:PORT" returned under Linux an error of
the form

   Error: can't connect to SOMEHOST port PORT: operation now in progress

on connections to hosts where the DNS entries have multiple IP
addresses associated. This error only showed up on the first
connection attempt (e.g. after a server restart, or on no connections
to this host for e.g. a few hours), all later attempts with identical
parameters worked without problems. It turned out that sometimes -
while working through the associated IP addresses - the call
"getsockopt(sock, SOL_SOCKET, SO_ERROR, ...)"  retrieved errno 113 <No
route to host> from the socket, maybe related with routing table
lookup.

The new code avoids this error lookup by checking just for the
writable condition returned by poll().