Fix a bug caused be the low level refactoring leading to incomplete https transfers with connchan.
The problem was that due to the refactoring since the last release, the
low-level https operations were made strictly non-blocking, where before
these operations might have blocked in some situations (partial writes).
Partial writes were already working before this patch, but in certain
situations, we experienced a 0 byte partial operation, followed by an error like

   Error: spool: POSIX {unknown error} Success, channel conn451 send operation failed: Success

It turned out that was caused by an OpenSSL error "ssl3_write_pending:bad write retry",
which is issued, when an operation ending in an SSL_ERROR_WANT_WRITE was executed
with a different buffer pointer (the resubmission of partial written data
happens via Tcl). The issue was addressed via the OpenSSL mode flag
SSL_MODE_ACCEPT_MOVING_WRITE_BUFFER. See the comments in the source code
for more details and alternate approaches.